version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: pjd_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Opcional: Cargar script inicial de base de datos
      - ./sql/bd_pjd.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    container_name: pjd_flask
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - FLASK_ENV=development
      - SECRET_KEY=${SECRET_KEY}
      - BASE_URL=http://localhost:5000
      - RESEND_API_KEY=${RESEND_API_KEY}
    volumes:
      - .:/app
      - ./static/img:/app/static/img
      - /app/venv
volumes:
  db_data: